Repository BlackBeltTechnology/structured-map-proxy, pull requests merged in 2022-07, with the labels that each got.

#14 JNG-3834 Add newer CI scripts and documentation updated
  .github/CIFLOW.adoc
  .github/branches.png
  .github/build.png
  .github/create-release-on-master.png
  .github/create-release-tagged.png
  .github/labels.yml
  .github/merge-pr-tagged.png
  .github/release.png
  .github/workflows/build.yml
  .github/workflows/create-release-on-master.yml
  .github/workflows/jira-description-to-pr.yml
  .github/workflows/merge-pr-tagged.yml
  .github/workflows/release.yml
  .github/workflows/sync-labels.yml
  LICENSE
  README.adoc
  pom.xml
Labels: documentation

#16 [RELEASE] Set develop version to: 1.1.0
  pom.xml
Labels: release, automated pr

#15 [RELEASE] Release version: 1.0.6 to master
  .classpath
  .github/CIFLOW.adoc
  .github/branches.png
  .github/build.png
  .github/create-release-on-master.png
  .github/create-release-tagged.png
  .github/labels.yml
  .github/merge-pr-tagged.png
  .github/release.png
  .github/workflows/build.yml
  .github/workflows/create-release-on-master.yml
  .github/workflows/jira-description-to-pr.yml
  .github/workflows/merge-pr-tagged.yml
  .github/workflows/release.yml
  .github/workflows/sync-labels.yml
  .gitignore
  .maven.xml
  .mvn/extensions.xml
  .mvn/jvm.config
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  .project
  LICENSE
  README.adoc
  local-build.sh
  local-release.sh
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/hu/blackbelt/structured/map/proxy/MapProxy.java
  src/test/java/hu/blackbelt/structured/map/proxy/MapBuilderProxyTest.java
  src/test/java/hu/blackbelt/structured/map/proxy/MapProxyTest.java
  src/test/java/hu/blackbelt/structured/map/proxy/entity/Event.java
  src/test/java/hu/blackbelt/structured/map/proxy/entity/User.java
  wercker.env.sample
  wercker.yml
Labels: release, automated pr

#18 JNG-3844 Fixing optional Enum handling
  src/main/java/hu/blackbelt/structured/map/proxy/MapProxy.java
  src/test/java/hu/blackbelt/structured/map/proxy/MapProxyTest.java
  src/test/java/hu/blackbelt/structured/map/proxy/entity/User.java
Labels: fix
